#!/bin/bash

# save_monitor workspace(0-index) monitor(0 is primary)
berryc save_monitor 0 0
berryc save_monitor 1 0
berryc save_monitor 2 1

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       0
berryc edge_gap         0 30 0 0

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    000000
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Fantasque Sans Mono-14"

nitrogen --set-zoom-fill --random ~/wallpapers --save &
xrdb -merge ~/.Xresources
